### ISSUE TITLE
Silo-Kapazitäten werden nicht angezeigt

### ISSUE THREAD

**Issue by CREEATION** [PCS-Sprinter/FS19-Puur-Nederland#11]
![grafik](https://user-images.githubusercontent.com/3277769/58768546-3a8a1b80-859d-11e9-9b2b-e7cdf74548ab.png)

**Comment by PCS-Sprinter** [comment]
Es gibt zwei verschiedene Anzeigen für die Silo-Kapazitäten.
1. Silos intern und 2. Silos extern.
Die Kapazität der internen Silos werden angezeigt, sobald man ingame ein eigenes Silo kauft und auf der Map platziert.
Die Kapazität für externe Silos wird nur angezeigt wenn auch externe Silos existieren. Bei einer originalen Giants-Map, gibt es externe Silos z.B. an den Bahnstationen.
