### ISSUE TITLE
Grass komt durch die mauer

### ISSUE THREAD

**Issue by BlackTiger63** [PCS-Sprinter/FS19-Puur-Nederland#12]
By Mike.
![afbeelding](https://user-images.githubusercontent.com/25569491/58768612-5641f180-859e-11e9-8dd4-3e099ef486cb.png)

![afbeelding](https://user-images.githubusercontent.com/25569491/58768733-f6e4e100-859f-11e9-836b-adef00d2e49a.png)

![afbeelding](https://user-images.githubusercontent.com/25569491/58768736-02d0a300-85a0-11e9-85d5-fc6f5252ef24.png)

![afbeelding](https://user-images.githubusercontent.com/25569491/58768741-0cf2a180-85a0-11e9-9cde-67a8227b0ad5.png)

**Comment by BlackTiger63** [comment]
Fixed by pull request von Mike wenn alles richtig ist. Nur photo 2 is nicht fixed.

**Comment by CREEATION** [comment]
Alles klar, schauen wir uns die Tage mal an. Super!

**Comment by BlackTiger63** [comment]
War den testserver von den neuen master vorsehen? Weill auf den testserver ist das grass was Mike gelösht had wieder zurück.

**Comment by CREEATION** [comment]
Der Pull Request wurde noch nicht übernommen, unteranderem weil Bild 2 damit noch nicht gefixt ist. Bitte noch etwas Geduld :see_no_evil:

**Comment by BlackTiger63** [comment]
Oh kein problem. Ich dachte das war schon geschehen weill ich hatte ein mail bekommen mit die meldung "pull request merged into master". Aber dann ist alles gut. :)
