### ISSUE TITLE
Kann kartoffeln nicht entladen

### ISSUE THREAD

**Issue by BlackTiger63** [PCS-Sprinter/FS19-Puur-Nederland#17]
![afbeelding](https://user-images.githubusercontent.com/25569491/58768773-7f638180-85a0-11e9-8c53-711d2ebeb819.png)

**Comment by PCS-Sprinter** [comment]
Auf dem Kartoffelhof können zwischen den Hallen unter der Überdachung Kartoffeln entladen werden.
![grafik](https://user-images.githubusercontent.com/51075190/59878481-b3b0ad80-93a8-11e9-9237-24c78e6c13ce.png)

In der zweiten großen Halle auf dem Hof können auch Kartoffeln entladen werden.
![grafik](https://user-images.githubusercontent.com/51075190/59878529-d5aa3000-93a8-11e9-946e-7b30a194ce64.png)

In der vorderen ersten Halle geht es noch nicht, da wahrscheinlich dort der entsprechende Eintrag in der xml fehlt.

**Comment by CREEATION** [comment]
Da es im LS19 noch keine Mods o.Ä. gibt welche dafür sorgen, dass man Sachen anständig abladen kann (und diese Füllmengen auch in der Statistik registriert, sowie optisch korrekt auf dem Boden dargestellt werden), wurde hier improvisiert.

Eine große Halle (ohne die Abtrennung in der Mitte wie im ersten Screenshot) wurde komplett entfernt. Dafür wurde ein kleines Silo (mit doppelter Kapazität), sowie eine Silo-Erweiterung platziert. Dabei wurde das Drumherum optisch entsprechend angepasst, damit es nicht so leer aussieht. (Screenshots folgen eventuell morgen)
