### ISSUE TITLE
Schafe fressen von betonboden

### ISSUE THREAD

**Issue by BlackTiger63** [PCS-Sprinter/FS19-Puur-Nederland#18]
![afbeelding](https://user-images.githubusercontent.com/25569491/58768780-97d39c00-85a0-11e9-8865-ab951e5ec1b6.png)

**Comment by CREEATION** [comment]
@BlackTiger63 @MikeNLK @PCS-Sprinter Ist das so in Ordnung? :thinking:

![grafik](https://user-images.githubusercontent.com/3277769/59197079-a9183c00-8b90-11e9-8368-04594a967322.png)

**Comment by BlackTiger63** [comment]
@PCS-Sprinter Gibts kein gezeichnetes stroh dan?
Wenn nein dan ist es so guht denke ich. Ist ja eigentlich ein fehler von LS19.
Hoffentlich wächst das gras icht höher dann im stall sonst konnte das vielleicht probleme geben und kann man das besser weg lassen.

**Comment by CREEATION** [comment]
@BlackTiger63 Das Gras wäre so nun statisch. Stroh als rohe Textur habe ich nicht gefunden, deshalb habe ich nicht nur normales Gras, sondern auch etwas zertrampeltes Gras gezeichnet. Wäre wie gesagt eine temporäre Lösung :-)

**Comment by BlackTiger63** [comment]
@CREEATION Ist prima, sieht gut aus!
