### ISSUE TITLE
Plane zur silage wird nicht ganz aufgedeckt beim wegholen

### ISSUE THREAD

**Issue by BlackTiger63** [PCS-Sprinter/FS19-Puur-Nederland#21]
Hier ist ein foto von die stelle befor das seil noch rüber gelegt wurde.
Abdecken geht gut und ganz. Aber aufdecken (wegholen) passiert nur teilweise.
- Könnte möglich was zu tun haben mit gras was durch kommt an die andere seite vom betonwand
- Könnte möglicherweise auch passieren bei die andere silage stelle hinter die andere kühewiese (noch nicht getested)

![afbeelding](https://user-images.githubusercontent.com/25569491/58768916-08c78380-85a2-11e9-89bb-47b0c205230f.png)

**Comment by BlackTiger63** [comment]
![afbeelding](https://user-images.githubusercontent.com/25569491/58769715-e2a5e180-85a9-11e9-9bf3-279190e0aece.png)

Ist bereits untersucht und bestätigt.
Bei den kleinen silo nahe die Zägerei ist das gleiches problem.
Ich kan am anfang die R drücken zum seil abnehmen und am ende, aber in die mitte nicht.
Ich frage mich sowieso ob das nicht alles ab gehen müsste mit nur 1 mal auf der R drücken.
Foto is von den kleinen silo:
![afbeelding](https://user-images.githubusercontent.com/25569491/58769955-fd795580-85ab-11e9-84b2-283442239853.png)

**Comment by BlackTiger63** [comment]
Neu getested nach den 1.4 update. Leider ist das problem nicht behoben.

**Comment by PCS-Sprinter** [comment]
Ich habe das heute getestet.

Plane drüber bei 100% - okay >
![grafik](https://user-images.githubusercontent.com/51075190/59868354-0a11f200-9391-11e9-872f-c5f134aafd0a.png)

Plane weg bei 100% Silage >>
![grafik](https://user-images.githubusercontent.com/51075190/59868432-2ca40b00-9391-11e9-82bd-d78b80a72a0e.png)

Es deckt jeweils am vorderen Rand die weiße Plane weg und das ist auch eigentlich richtig so. Sobald man nun die fertige Silage aus dem Silo schaufelt, verschwindet die restliche Plane wenn man mit der Schaufel an die Plane kommt. Und zack - die Silage ist vollkommen frei zugänglich.
>>>
![grafik](https://user-images.githubusercontent.com/51075190/59868625-a76d2600-9391-11e9-8186-0ceff7fa5e49.png)


Somit kein Fehler mit der Plane, sondern einfach nur nahe an der Wirklichkeit.
