### ISSUE TITLE
Manchmal können farzeuge nicht von jeden ge- oder entladen werden

### ISSUE THREAD

**Issue by BlackTiger63** [PCS-Sprinter/FS19-Puur-Nederland#22]
Sprinter ist dies bekannt.
Beim testen haben wir gesehen das reihenweise er oder ich ein anhänger oder LKW nicht laden oder entladen könnten.
Ursache unbekannt.
Problem ist auch das verschiedene male es kein problem gab und plötzlich war es nicht mer möglich.

**Comment by BlackTiger63** [comment]
Manchmal geht es wieder gut wen ein par mal auf die R gedrückt wird oder anders gefahren wird.
Silo is nachher hingesteld zum schneller testen zu können also vielleicht collidiert da noch etwas. Die steht nicht in den originellen mappe rein.

**Comment by PCS-Sprinter** [comment]
Kann nicht mehr reproduziert werden, nach Update 1.4.0.0.
