### ISSUE TITLE
Kühe sound wo kein sound sein sollte

### ISSUE THREAD

**Issue by BlackTiger63** [PCS-Sprinter/FS19-Puur-Nederland#25]
Feld 38 östlich. Da ist keine farm irgendwo in die nähe.
Doch werden ab diesen punt und mehr nach rechts (richtung ende der mappe) das lauten der kühe gehört.
![afbeelding](https://user-images.githubusercontent.com/25569491/58770017-885a5000-85ac-11e9-8568-e306a3d8c551.png)

Abbildung zur position.
![afbeelding](https://user-images.githubusercontent.com/25569491/58770026-96a86c00-85ac-11e9-8aef-1707172a2a5a.png)

**Comment by CREEATION** [comment]
@PCS-Sprinter die Sounds sind hier definiert: https://github.com/PCS-Sprinter/FS19-Puur-Nederland/blob/master/maps/Nederland_sound.i3d
