### ISSUE TITLE
Erdfrüchtelager, kein entladetrigger vorhanden

### ISSUE THREAD

**Issue by BlackTiger63** [PCS-Sprinter/FS19-Puur-Nederland#26]
Bei dem Erdfrüchtenlager (farm 6, rote farm) ist kein entlademöglichkeit für erdfrüchte wie kartoffel.

**Comment by PCS-Sprinter** [comment]
Im Erdfrüchtelager (in den Kühlkammern) können Kartoffeln und Zuckerrüben entladen werden. Zwiebel und Möhren noch nicht, aber das dürfte ein entsprechender Eintrag in der xml dann auch ermöglichen. Ich kümmere mich drum.

![grafik](https://user-images.githubusercontent.com/51075190/59877017-3a638b80-93a5-11e9-939b-2b71d5e4781e.png)

**Comment by CREEATION** [comment]
Die Lösung wurde improvisiert, siehe [diesen Kommentar](https://github.com/PCS-Sprinter/FS19-Puur-Nederland/issues/17#issuecomment-504707163). Eine Halle wurde entfernt, der Rest blieb wie gehabt. Ein kleines Silo und eine Silo-Erweiterung wurden platziert, die Umgebung optisch etwas angepasst.
