### ISSUE TITLE
modDesc Map Beschreibung veraltet

### ISSUE THREAD

**Issue by CREEATION** [PCS-Sprinter/FS19-Puur-Nederland#31]
Siehe https://github.com/PCS-Sprinter/FS19-Puur-Nederland/blob/master/modDesc.xml#L33
Es sind mittlerweile mehr als 5 Farmen.

**Comment by CREEATION** [comment]
**EN:** The map is based off of the beautiful Dutch landscape and villages. There are multiple farms for you to work on, including a dairy cattle and chicken farm, a horse stud, a sheepfold and much more. Enjoy your stay on Pure Netherlands!

**DE:** Die Karte basiert auf der wunderschönen niederländischen Landschaft und deren Dörfern. Es existieren mehrere Farmen auf denen Sie arbeiten können, unteranderem eine Milchvieh & Hühnerfarm, ein Pferdegestüt, ein Schafhof und noch viele mehr. Genießen Sie Ihren Aufenthalt auf Reine Niederlande!

**Comment by BlackTiger63** [comment]
**NL:** Deze map is gebaseerd op een prachtig Nederlands landschap en dorpen. Er zijn meerdere boerderijen waarop je kunt werken, onder andere een melkvee & kippenboerderij, een paardenstoeterij, een schapenhouderij en nog veel meer. Geniet van uw verblijf op Puur Nederland!

**Comment by CREEATION** [comment]
fixed in https://github.com/PCS-Sprinter/FS19-Puur-Nederland/commit/c262a934848a280e0029b9e2140a36d864de7a9a
