### ISSUE TITLE
Frage: Wofür ist diesen trigger?

### ISSUE THREAD

**Issue by BlackTiger63** [PCS-Sprinter/FS19-Puur-Nederland#36]
Ist auf den pferdestuterei.
Bei trigger 1 wird wasser entladen für die pferde
Bei trigger 2 wird den rest entladen was die brauchen, also stroh, hafer und heu.

Bleibt 1 trigger mit die ??? dabei, da ist keine tür und wird nichts entladen, wofür wird der benutzt? Oder kan mann den einfach stehen lassen wenn nicht benuzt? Wird das keine collision geben wenn man da selber etwas stellen will mit einen trigger?

![trigger](https://user-images.githubusercontent.com/25569491/58997230-f6488680-87fb-11e9-831a-aa97da6a7907.jpg)

**Comment by CREEATION** [comment]
Der Trigger ist für Stroh :thinking:

![grafik](https://user-images.githubusercontent.com/3277769/59206968-62354100-8ba6-11e9-8965-92b1c33266d2.png)
