### ISSUE TITLE
Salat flakkert licht/dunkel in die kasse

### ISSUE THREAD

**Issue by BlackTiger63** [PCS-Sprinter/FS19-Puur-Nederland#37]
Wenn man in die kasse ist neben den pferdestuterei und man lauft da herum, dan flakkert den salat wie ein wilder.
Dunkel und grün wenn man lauft oder die maus bewegt.
Ist nur in den beiden salat kassen, nicht in den beiden tomatenkassen.
Ist auch von ausserhalb sichtbar.

![afbeelding](https://user-images.githubusercontent.com/25569491/58997475-1b89c480-87fd-11e9-876e-97a6e9379d48.png)

halben meter weiter oder wenn man die maus minimal bewegt:
![afbeelding](https://user-images.githubusercontent.com/25569491/58997490-26dcf000-87fd-11e9-8a31-2abde5682409.png)

**Comment by CREEATION** [comment]
Duplikat von https://github.com/PCS-Sprinter/FS19-Puur-Nederland/issues/27
