### ISSUE TITLE
Schweinefarm futter niveau

### ISSUE THREAD

**Issue by BlackTiger63** [PCS-Sprinter/FS19-Puur-Nederland#38]
Ich weiss nicht ob das so sein sol aber wenn an eine seite volle kartoffeln geladen is siehe iech dies:
![afbeelding](https://user-images.githubusercontent.com/25569491/58999253-2fd1bf80-8805-11e9-8c0a-b3d5fd9c0ebf.png)

Aber da kann nichts mehr dabei von kartofflen.
Aber an die andere seite kan ich noch was kartoffeln abladen und dan sieht es so aus:
![afbeelding](https://user-images.githubusercontent.com/25569491/58999291-63144e80-8805-11e9-8b68-f7e80fc0a628.png)

Also entweder an die linke seite wird nicht gezählt, oder mann bekommt nur was zu sehen wenn man auch an den rechter stall was entladen had wo ich jetzt mit den trekker stehe auf die abbildung.
Das kommt mir aber komisch vor. Da musste es bei ein erste vollen abladung wenn da nichts mehr bei kann an die linke seite, doch mindestens halb vol angegeven werden, doch?
Und dies ist so bei allen futter was hinten abgeladen werden muss.

**Comment by BlackTiger63** [comment]
Ist weiter untersucht und bestätigt.
Wenn man richtung die schweinestallen guckt, dan nimmt den rechten stall alles ab aber da wirdt nichts gezählt, also wasser, stroh, macht nichts aus. Man kann alles abladen und wird voll aber nichts wird gezählt.
Nur beim abladen im linken stall geht es sowie es sein soll.

**Comment by CREEATION** [comment]
Hallo! Das Problem kann nicht reproduziert werden, scheint alles zu funktionieren.

Links:
![grafik](https://user-images.githubusercontent.com/3277769/59939551-a0f5b180-9458-11e9-9084-bbbc35d48ca6.png)

Rechts:
![grafik](https://user-images.githubusercontent.com/3277769/59939579-b4088180-9458-11e9-9935-701a7bcae018.png)

Habe Kartoffeln etc. auch einzeln ohne Probleme entladen können, egal in welcher Reihenfolge.

- Thomas

**Comment by BlackTiger63** [comment]
Wo hast du den getested? Geht noch immer nicht.
Einfach zu reproducieren.

![afbeelding](https://user-images.githubusercontent.com/25569491/59952050-2db16700-947b-11e9-9444-bec7c5d857b8.png)

![afbeelding](https://user-images.githubusercontent.com/25569491/59952064-3e61dd00-947b-11e9-8ba8-06017e7d8241.png)

**Comment by BlackTiger63** [comment]
Versuche mal dort wo ich stehe eine halbe portion weizen to entladen. Dan kann man sehen das dies nicht angegeben wird.
An die andere ecke für den anderen stall werden alle mengen, auch kleine, gleich registriert.

**Comment by CREEATION** [comment]
Auf meinem Screenshot sieht man doch, dass ich alles abladen konnte. Ist alles voll geworden, an beiden Ställen. :thinking:

**Comment by BlackTiger63** [comment]
Verstehe ich nicht. Wenn ich auf die stelle wo ich bin was abliefere wird gar nichts registriert.
Nirgendwo an die trigger von diesem linker stall (links auf den bild) wird irgendwas registriert bei mir. Das ist toch fremd oder? Nur wenn ich rechts etwas abliefere dan geht der meter hoch.
Und bei du alles in ordnung? Fremd.
Mal undersuchen wie das bei anderen ist vielleicht?

**Comment by PCS-Sprinter** [comment]
Richard, du musst die Tabelle für Stall 2 auch separat aktivieren/anklicken, damit du den Inhalt sehen kannst. Bei deinem Beispiel bist du immer nur in der Tabelle von Stall 1. Es funktioniert dort alles wie es sein soll.

![grafik](https://user-images.githubusercontent.com/51075190/59965757-a4e60a00-9512-11e9-99c3-8c617e895647.png)

**Comment by BlackTiger63** [comment]
Halo Walter.
Ich bin jetzt im spiel und frage Mike mal rüber zum gucken, weill ich habe das so nicht. Und ich habe gerade die letzten files runter geladen und neu gestartet.
Bei mir sind keine 2 Stalle, nur einen sichtbar???
![afbeelding](https://user-images.githubusercontent.com/25569491/59965900-a31d4600-9514-11e9-9cd6-a7f7664f9b00.png)

**Comment by BlackTiger63** [comment]
Haaaa... das hatte ich nicht gesehen.
Wusste ich nicht, jetzt gerade übersehen! Oke ist ganz in ordnung. Mein fehler.
Danke, kan geschlossen und gelöst bleiben!
Entschuldige mich.
