### ISSUE TITLE
Iconen verschwinden bij Fahrzeugladen

### ISSUE THREAD

**Issue by BlackTiger63** [PCS-Sprinter/FS19-Puur-Nederland#40]
Innerhalb und ausserhalb sind die gelben iconen verschwunden.
![afbeelding](https://user-images.githubusercontent.com/25569491/59067959-39b1fc00-88b3-11e9-9419-d76991dcb9b2.png)

**Comment by BlackTiger63** [comment]
@CREEATION 
Ist noch nicht völlig erladigt:
![afbeelding](https://user-images.githubusercontent.com/25569491/59210866-cfe56b00-8bae-11e9-962a-c408c7ae650c.png)

Screenshot gerade gemacht. Noch kein icoon in die garage.

**Comment by CREEATION** [comment]
![grafik](https://user-images.githubusercontent.com/3277769/59211807-13d96f80-8bb1-11e9-9ba8-1ae57d5f877a.png)

Der Dedi-Server wird nicht automatisch aktualisiert. Bei einem Update des Servers gibt @PCS-Sprinter im Discord bescheid. :+1:
