### ISSUE TITLE
Titel Lohnunternehmen an falscher stelle.

### ISSUE THREAD

**Issue by BlackTiger63** [PCS-Sprinter/FS19-Puur-Nederland#41]
Das Lohnunternehmen ist nicht da wo den kreuz ist, das felt ist auch leher.
Aber das Lohnunternehmen ist da wo den dikken pfeil steht, neben feld 7. Da sind auch die garages dafür gebaut.

![lohnunternehmen](https://user-images.githubusercontent.com/25569491/59068779-68c96d00-88b5-11e9-9d62-efa825687b44.jpg)

**Comment by PCS-Sprinter** [comment]
* Farmlands neu gezeichnet, Lohnunternehmen versetzt
* Landkarte am Startpunkt (Farmhaus) aktuallisiert
