### ISSUE TITLE
Bunkersilo TipCollision fehlt

### ISSUE THREAD

**Issue by CREEATION** [PCS-Sprinter/FS19-Puur-Nederland#42]
![afbeelding](https://user-images.githubusercontent.com/25569491/58768728-e03e8a00-859f-11e9-8c65-1e54fa7fe9a4.png)

Das große Bunkersilo soll entfernt/ersetzt werden.

**Comment by BlackTiger63** [comment]
Doppeltsilo soll geändert werden in ein einzelnen silo oder sonnst 2 einzelnen silos.
Mike sagte es sind diesen:
/data/placeables/bunkerSilo/bunkerSiloLarge.i3d

**Comment by PCS-Sprinter** [comment]
Statt Doppelsilo zwei Einzelsilos eingebaut und Groundkollision in der Mitte hinzugefügt. Silo ist jetzt dicht.

**Comment by PCS-Sprinter** [comment]
![grafik](https://user-images.githubusercontent.com/51075190/59965494-191eae80-950f-11e9-8f67-64ee4d5a28a0.png)
