### ISSUE TITLE
Fahrzeuge Singleplayer FarmIDs

### ISSUE THREAD

**Issue by CREEATION** [PCS-Sprinter/FS19-Puur-Nederland#43]
Aktuell gibt es [mehrere Startfahrzeuge](https://github.com/PCS-Sprinter/FS19-Puur-Nederland/blob/master/NederlandVehicles.xml), allerdings kann man die Fahrzeuge mit einer `farmId` die nicht `1` ist nicht nutzen im Singleplayer.
Entweder Startfahrzeuge bis auf die mit `farmId="1"` entfernen via Script, oder alle auf `1` setzen.

**Comment by CREEATION** [comment]
@BlackTiger63 @MikeNLK @PCS-Sprinter Lieber alle Startfahrzeuge im Singleplayer auf `1` setzen, oder alle bis auf ein Fahrzeug entfernen? :thinking:

**Comment by BlackTiger63** [comment]
@CREEATION Mike möchte gerne Startfahrzeuge in die mappe behalten.
Aber ich verstehe es nicht ganz. Wenn ich in den link (mehrere Startfahrzeuge) gucken gehe, da stehen alle fahrzeuge auf farmid=1 nur "baseMaterial" haben verschiedene id's.
Also ist den https://github.com/PCS-Sprinter/FS19-Puur-Nederland/blob/master/NederlandVehicles.xml schon von dir bearbeitet oder....? Weil da sehe ich keine startfahrzeuge mit eine andere id dan 1.

**Comment by CREEATION** [comment]
@BlackTiger63 @MikeNLK die `farmId` ist bei jedem unterschiedlich (stehen auf `1`-`5`, schau noch mal genau hin. Hast du vielleicht mit `propertyState` verwechselt :wink: :see_no_evil:

**Comment by BlackTiger63** [comment]
Mike sagte da standen viel mehr dan 5 Fahrzeuge, oder zählen anhänger nicht als fahrzeuge?
Auf die Bauernhöfe stehen auch anhänge, die wil er alle auch gerne behalten wenn das geht.
Aber jetzt ist nicht deutlich ob die anhänger auch als fahrzeuge zählen oder nicht. Wenn nicht dan gerne Möglichkeit 2 machen.

**Comment by PCS-Sprinter** [comment]
Im Singleplayer gibt es 20 Startfahrzeuge (incl. Maschinen u. Anhänger) und die bleiben natürlich auch so wie es immer war. Die 5 Fahrzeuge (nur Pick-Ups) aus dem Multiplayer entfallen.

**Comment by BlackTiger63** [comment]
Ah oke. Wenn es nur Pick-Ups sind die entfallen ist es kein problem.
Nur der eine auto beim startfarm muss bleiben wenn geht (und die machinen beim garage/shop natürlich).

**Comment by BlackTiger63** [comment]
Ist zugewiesen an singleplayer, aber im multiplayer gibt es momentan auch keine startfahrzeuge (sowieo Machinen u. Anhänger) und die waren vorhin schon da bei die garage (standen draussen), die möchte mann auch gerne zurück.

**Comment by PCS-Sprinter** [comment]
Im Multiplayer gibt es acht fest definierte Farmen/Höfe und da kauft sich doch jeder dann selber im Shop seine eigenen Startfahrzeuge die er entsprechend seiner Farm braucht. Ansonsten müssten doch 8 x 20 Startfahrzeuge (160 !!!) hingestellt werden. Das geht so nicht - jeder kauft selber was er möchte :-)

**Comment by BlackTiger63** [comment]
Ja so hat Mike denk ich gar nicht gerechnet. Und wenn 8 höfe sind und einer klaut sich alle startfahrzeuge wen nur die pahr bei den shop stehen, wurde das nicht fair für die anderen sein. Stimmt auch.
Ich hab je keine ahnung, ist mein erstes mal mit diesem spiel. :)
Danke für die erklärung.

**Comment by CREEATION** [comment]
Die fünf Pick-Ups wurden im Single- und Multiplayer entfernt. Maschinen & Anhänger (und das Startfahrzeug an der Startfarm) sind wieder im Singleplayer vorhanden.
