### ISSUE TITLE
Falsche texture wiedergabe nach ernten

### ISSUE THREAD

**Issue by BlackTiger63** [PCS-Sprinter/FS19-Puur-Nederland#45]
Glower15 war Sonntag Zuckerrüben ans ernten und kalk streuen zur gleicher zeit. Feld war noch nicht fertig.
Wenn er heute (nach dem 1.4) zurück kam, war da plötzlich für den rest Mais statt Zuckerrüben.

![afbeelding](https://user-images.githubusercontent.com/25569491/59785279-b043f600-92c4-11e9-948b-48af389f6ca2.png)

Aber wenn er hin gelaufen ist, da ist den Mais verschwunden und kamen wieder Zuckerrüben sichtbar.
Also nur an erster stelle war kurz den falschen texture wieder gegeben.
Konnte das verursacht sein durch den 1.4 update?

**Comment by PCS-Sprinter** [comment]
In der i3d den Mais komplett vom Feld entfernt.
