### ISSUE TITLE
Kleine unebenheit im Feld 27

### ISSUE THREAD

**Issue by BlackTiger63** [PCS-Sprinter/FS19-Puur-Nederland#46]
Feld 27 kleine unebenheid, ist nicht flach. Fast am anfang wo man des feld rein fährt.

![afbeelding](https://user-images.githubusercontent.com/25569491/59789636-93acbb80-92ce-11e9-998b-0ab54f34eb2c.png)

**Comment by PCS-Sprinter** [comment]
* Hügel geglättet.
![grafik](https://user-images.githubusercontent.com/51075190/59940202-5d9c4280-945a-11e9-9c3b-27025d1e4419.png)
