### ISSUE TITLE
Feld 45 is nicht zugänglich!

### ISSUE THREAD

**Issue by BlackTiger63** [PCS-Sprinter/FS19-Puur-Nederland#48]
Man kann feld 45 nicht betreten, ist umgeben durch wasser.
Ist kein grosses problem, weil wenn mann das land daneben kauft kan men das zusetzen.
Aber vielleicht für ein zukünftigen patch schon hier melden.
Gefunden durch Gerald.
![afbeelding](https://user-images.githubusercontent.com/25569491/59981525-e820a580-9604-11e9-9326-3cd9dafa78c2.png)

**Comment by PCS-Sprinter** [comment]
Feld 45 ist nun im nordwesten und nordosten von der Strasse aus zugänglich.

![grafik](https://user-images.githubusercontent.com/51075190/60193563-2f42ac80-9838-11e9-899e-1eed4cc170db.png)

![grafik](https://user-images.githubusercontent.com/51075190/60193615-441f4000-9838-11e9-8d08-b099213951d2.png)
