### ISSUE TITLE
1 linie weizen(?) auf den mais field 25.

### ISSUE THREAD

**Issue by BlackTiger63** [PCS-Sprinter/FS19-Puur-Nederland#49]
Weiss nicht gut wie das zu umschreiben auf Deutsch aber das foto macht viel deutlich denk ich.

![afbeelding](https://user-images.githubusercontent.com/25569491/59982370-4489c200-9611-11e9-8526-fe82fa5bb667.png)

**Comment by PCS-Sprinter** [comment]
Da stand jeweils eine Reihe Mais. Diese überflüssigen Reihen sind entfernt.

![grafik](https://user-images.githubusercontent.com/51075190/60193750-8052a080-9838-11e9-807e-7b279facb874.png)

![grafik](https://user-images.githubusercontent.com/51075190/60193776-8779ae80-9838-11e9-8b0a-e265739dde1f.png)
