### ISSUE TITLE
Michvee und Kippenfarm schönheitsfehler (tür nicht da)

### ISSUE THREAD

**Issue by BlackTiger63** [PCS-Sprinter/FS19-Puur-Nederland#51]
Kein grosses problem, nur einen kleinen schönheitsfehler.
Ebentuell wenn möglich eine tür rein bauen in nächste version, oder einfach schliessen wenn das nicht geht weil da auch ein tiertrigger ist.
![afbeelding](https://user-images.githubusercontent.com/25569491/60128233-6eb6bd80-9792-11e9-920a-0bedcbb7e76c.png)

**Comment by PCS-Sprinter** [comment]
Es wurde ein zusätzliches Schiebetor mit Funktion eingebaut.

![grafik](https://user-images.githubusercontent.com/51075190/60194927-86498100-983a-11e9-8ecb-12a6f954a39a.png)

![grafik](https://user-images.githubusercontent.com/51075190/60194947-8ea1bc00-983a-11e9-8570-163bbd9f9d84.png)

**Comment by PCS-Sprinter** [comment]
Das Schiebetor wurde geändert und geht jetzt zur richtigen Seite auf, nach links, entsprechend der Laufschiene.

![grafik](https://user-images.githubusercontent.com/51075190/60202165-4be7e000-984a-11e9-9894-0e05181d3033.png)
