### ISSUE TITLE
Money Skript Fehler

### ISSUE THREAD

**Issue by PCS-Sprinter** [PCS-Sprinter/FS19-Puur-Nederland#8]
update 2019-06-02 03:31

LUA call stack:
dataS/scripts/FSBaseMission.lua (2662) : printCallstack
dataS/scripts/placeables/Placeable.lua (1115) : addMoney
dataS/scripts/environment/Environment.lua (212) : hourChanged
dataS/scripts/BaseMission.lua (1590) : update
dataS/scripts/FSBaseMission.lua (1971) : update
dataS/scripts/missions/mission00.lua (469) :
dataS/scripts/main.lua (1863) : update
Error: Can't change money of spectator farm

**Comment by CREEATION** [comment]
https://github.com/PCS-Sprinter/FS19-Puur-Nederland/commit/eef5a64353ca30312762aa3e4c11af80e895d187

Windmühlen und Gewächshäuser haben automatisch Geld generiert, obwohl sie keiner Farm zugeordnet waren.

**Comment by CREEATION** [comment]
Fehler wurde nun via LUA gelöst, damit Gewächshäuser weiterhin nutzbar sein können. https://github.com/PCS-Sprinter/FS19-Puur-Nederland/commit/029911725be5057bc49f5422812a6f39a860d22f
